/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShooterProfilesIndexRouteImport } from './routes/shooter-profiles/index'
import { Route as AccountManagementRouteImport } from './routes/account/management'

const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShooterProfilesIndexRoute = ShooterProfilesIndexRouteImport.update({
  id: '/shooter-profiles/',
  path: '/shooter-profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountManagementRoute = AccountManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/timer': typeof TimerRoute
  '/account/management': typeof AccountManagementRoute
  '/shooter-profiles/': typeof ShooterProfilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/timer': typeof TimerRoute
  '/account/management': typeof AccountManagementRoute
  '/shooter-profiles': typeof ShooterProfilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/timer': typeof TimerRoute
  '/account/management': typeof AccountManagementRoute
  '/shooter-profiles/': typeof ShooterProfilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/timer'
    | '/account/management'
    | '/shooter-profiles/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/timer' | '/account/management' | '/shooter-profiles'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/timer'
    | '/account/management'
    | '/shooter-profiles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  TimerRoute: typeof TimerRoute
  ShooterProfilesIndexRoute: typeof ShooterProfilesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shooter-profiles/': {
      id: '/shooter-profiles/'
      path: '/shooter-profiles'
      fullPath: '/shooter-profiles/'
      preLoaderRoute: typeof ShooterProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/management': {
      id: '/account/management'
      path: '/management'
      fullPath: '/account/management'
      preLoaderRoute: typeof AccountManagementRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountManagementRoute: typeof AccountManagementRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountManagementRoute: AccountManagementRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  TimerRoute: TimerRoute,
  ShooterProfilesIndexRoute: ShooterProfilesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
